language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: Oa5UGAFOCXv7kfgQYxNXHsLptxQxb1RXyGAq6Xv1JJOUele8Zf1E/Argr1+dtupxSMURYSY7mnDgX26BwjUgk4gk+1l2KRfLLZoS7T+WU+l7sUlzAAp6XCvj/bTjWT/OGq5Nwaf5dSJZyc/yGEMVK+vd6q/xoNElre72Md1/1Nc8t0tLpKVN00D9hBr24hRqhz76DnTCYP4Tl4k6kUz7EsEICcv0/i7j+2MGGVcGvBkX7E4y2UGO+h3CQW9Q7quwEO0z5WWGckaBP2sIrtBzNc+/tN7Oc6uy8O+WXYK56sf9GW4jNK1+IEW5hfEhyxChdT58YtjyDPzI+4sDf0LEBEYAzDFhz06ce5RnxZnzG/OubQ5UYvcphUpvXMgGCfOWrEu3loZfnIPjoblSMUkyzFk2uGbmdfaqNQTJ6VzFllT8GlnSojddmx3Ljpxv90G0pAZyEUvKyJQIlzETm6TgyRlawUMp9gbzRqvFWkideAWLRLBojMBjZe1JxObugMsEOIr0ylqId5dmv975Yl5lR+m2tKsjxAizmgQ8qMLMvajmmeuso1HdKCvTj2hTp//WQC+5Kw6JE0GaOePml9zSMsZ9F8wjPTkc2Qi8WveJNbTlcO4Ev0tcmbIOacbpA4pZHdU1pw7Ni76UTvEYzz5Hwe1FVqjDb0hWsLJPPnBc9HM=
  - secure: cLxPyzJy1lJB1FvTFXS9THGCtMug7qAwtB+YixLHDqdgfZElnc7zfjjtc9h093EhkwYeg8Md9ajjKp7LtGhmzOC0oc1nPteBE9mpAnmz8UxLyMiPZFRuRjmM8GRoAeGtoPz2tzn25FeJVCo7JVwej4J0HLttYnRd2wwc4bmh9/v89BSR8RNfllU8v8I7bcD4e4W0O9bnyaEIu8A/LFgCGHLKP04sw6wL6uZGbn4kAiqi22y1p7xDYSimAeZP0XF3WlOf3MOavIaLNJlU0N8aaQjZsXA8pPXFM0tGk/waz+8I4dfWN2LgqvQWBsjehfkyyzP9lDTjcOJ+fY2B9Nk8UiK3Pmm1puyGjz/AQ+a6XCLzbYV7nCtC/rQ0IQ4FdM4np6Y5XV+wPjrIuyEBM3AalOroYoaCEu9K95V41QI7abNFEHzCNHp6tqMNWojwlKoPvPsbiOVrtGc42+Z+ez0hW9vEU47fFBWSZj1CbixdQjmRkBgQKC0Oa/NL5MuZcfsStMrDdE+1Kl0UfGIVWgJ7CcHsJVR8GySS3m9jHmkHBRRYPbWA27MmN8Gd89W8nT9TeRhLGJHkYANlJjNNeDfodUGgfavBQaEs3jjPlD3perr1dyBdFFAbAxLnaaH2Odx/Xmj+cxpPXIrhNfes+9idNFyFq2ZNo0DDfMR7/tF1nnM=
